### ISSUE TITLE
gallery.cnf leads to XSS

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/gallery#295]
``` yaml

---
# Gallery configuration file
information:
  description: This <script>alert(1)</script>is an **album description** which is only shown if there is no `description_link`
  copyright: Copyright 2003-2015 [interfaSys sàrl](javascript:alert(1\)), Switzerland
  inherit: yes
sorting:
  type: date
  order: des
  inherit: yes
features:
  external_shares: yes
  native_svg: yes
```

Personally I'd advise to remove this info stuff as it can easily lead to further security issues while offering few advantages.

cc @jancborchardt
